### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by najwahelsinki** [IRCHispano/ircd#1]
Estuve revisando e instale IRCuh en mi vps, con los servicios etc, pero revisando en tabla.z no se cambia el nombre de la red dice "IRC-Hispano" y tampoco puedo hacer /rehash siendo Global/Local me dice acceso denegado. Que tengo que hacer?

**Comment by zoltyvigo** [comment]
El Network se configura mediante la tabla f de Features. Antes estaba en la z, ahora en la f para migrar hacia el IRCh.

Las variables que se configuran en la F son:

```
#define BDD_ACTIVAR_IDENT                       "noident"

#define BDD_AUTOINVISIBLE                       "autousermodes"

#define BDD_MENSAJE_GLINE                       "msg_glined"

#define BDD_NICKLEN                             "nicklen"

#define BDD_NUMERO_MAXIMO_DE_CLONES_POR_DEFECTO "ipcheck_default_iline"

#define BDD_MENSAJE_DE_DEMASIADOS_CLONES        "ipcheck_msg_toomany"

#define BDD_OCULTAR_SERVIDORES                  "his_netsplit"

#define BDD_SERVER_NAME                         "his_servername"

#define BDD_SERVER_INFO                         "his_serverinfo"

#define BDD_NETWORK                             "network"

#define BDD_CANAL_OPERS                         "operschan"

#define BDD_CANAL_DEBUG                         "debugchan"

#define BDD_CONVERSION_UTF                      "utf8_conversion"

#define BDD_MENSAJE_DE_CAPACIDAD_SUPERADA       "msg_fullcapacity"

#define BDD_PERMITE_NICKS_RANDOM                "allow_random_nicks"

#define BDD_PERMITE_NICKS_SUSPEND               "allow_suspend_nicks"

#define BDD_CLAVE_DE_CIFRADO_DE_IPS             "ip_crypt_key"
```


Respecto al comando /rehash y demás asociados al +o, pues hay que asignar en la o-line del ircd conf la mascara de bits de los privilegios.
Revisando en el código veo que en la obtención de privilegios al recibir +o está incompleta en /oper  y que solo funciona si es mediante BDD.
A lo largo del día corregiré eso.

Hay un comando para ver los privilegios actuales con /PRIVS.

**Comment by zoltyvigo** [comment]
Corregido en la version u2.10.H.10.285
